#! /bin/sh

. ./prelude

archmagec wm -a "TEST-SWAP-A" 1024x512+0+0
archmagec wm -a "TEST-SWAP-B" 1024x512+0+512

archmagec monitor -f "TEST-SWAP-A"
window add 3

archmagec monitor -f "TEST-SWAP-B"
window add 2

nodes_a=$(archmagec query -N -m "TEST-SWAP-A")
nodes_b=$(archmagec query -N -m "TEST-SWAP-B")

archmagec desktop "TEST-SWAP-A:^1" -s "TEST-SWAP-B:^1"

[ "$(archmagec query -N -m 'TEST-SWAP-A')" = "$nodes_b" ] || fail "Wrong nodes in first monitor"
[ "$(archmagec query -N -m 'TEST-SWAP-B')" = "$nodes_a" ] || fail "Wrong nodes in second monitor"

window remove 3
archmagec monitor -f "TEST-SWAP-A"
window remove 2

archmagec monitor "TEST-SWAP-A" -r
archmagec monitor "TEST-SWAP-B" -r
