#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

archmagec monitor -d I II III IV V VI VII VIII IX X

archmagec config border_width         2
archmagec config window_gap          12

archmagec config split_ratio          0.52
archmagec config borderless_monocle   true
archmagec config gapless_monocle      true

archmagec rule -a Gimp desktop='^8' state=floating follow=on
archmagec rule -a Chromium desktop='^2'
archmagec rule -a mplayer2 state=floating
archmagec rule -a Kupfer.py focus=on
archmagec rule -a Screenkey manage=off
